#!/usr/bin/env ruby
require 'greybutton_palindrome'
require 'open-uri'

palindromes = open('https://cdn.learnenough.com/phrases.txt').readlines.select(&:palindrome?)
palindromes.each { |palindrome| puts "palindrome detected: #{palindrome}" }
File.write('palindromes_url.txt', palindromes.join)
