#!/usr/bin/env ruby
require 'open-uri'
require 'nokogiri'

# Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
# Especially useful for text-to-speech (both native and foreign).

url = ARGV[0]

abort 'Please, provide url' if url.nil?

doc = Nokogiri::HTML(open(url).read)
doc.css('.reference').each(&:remove)
content = doc.css('p').map(&:content).join("\n")
puts content
